services:
  trip_together_db:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_DB: 'trip_together_db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '54322:5432'
    networks:
      - backend
    volumes:
      - ./trip_together/postgres/data:/var/lib/postgresql/data

networks:
  kc:
    name: kc-network
    driver: bridge
  backend:
    name: back-network
    driver: bridge

